### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by serejkaaa512** [StoriqaTeam/eos#3]
- [x] implement Chain bindings
- [x] implement Console bindings
- [ ] implement Crypto bindings
- [ ] implement Database bindings
- [ ] implement System bindings
- [ ] implement Transaction bindings
- [ ] implement Priveleged bindings
- [ ] implement Memory bindings
- [ ] memory allocation
- [x] custom memory allocator
